### ISSUE TITLE
ERROR in app.android.js from UglifyJs Unexpected token: name (Feedback)

### ISSUE THREAD

**Issue by bm2ilabs** [EddyVerbruggen/nativescript-feedback#26]
Hi first of all thank you for the plugin , i am trying to use the plugin in nativescript-vue but i get this error when compiling .
```
ERROR in app.android.js from UglifyJs
Unexpected token: name (Feedback)
```

### Steps to reproduce the issue 
 1 - installing the plugin via npm 
 2 - adding the plugin 
```(Javascript)
import { Feedback } from 'nativescript-feedback'
```
3 - adding vue prototype
```
Vue.prototype.$feedback = new Feedback();
``` 

### Env

```(JSON)
    "nativescript-vue": "^1.2.0",
    "tns-core-modules": "3.4.1",
     "nativescript-feedback": "^1.2.0",
```

**Comment by budi7** [comment]
hi, sadly i facing the some issue here (with the ns-vue)
any workaround on it guys?

env: 

    "tns-core-modules": "~3.4.1",
    "nativescript-vue": "^1.3.1",
    "nativescript-feedback": "^1.3.9",

**Comment by EddyVerbruggen** [comment]
I'm using it like this without issues in a Vue project: https://github.com/EddyVerbruggen/footplr/blob/master/app/utils/feedback-util.ts

**Comment by budi7** [comment]
Hi Eddy, i found the problem was the uglify.js used in ns-vue version 1.3.1 not supporting the es6 things. Running on debug mode will not trigger any error, but hitting build did. 

My workaround is put try-catch block inside the web pack-config that handle the plugin. After that, the plugin back to work again.
*some advices are appreciated 

Last, thank you @EddyVerbruggen for such a great plugin 🎉🎉
