### ISSUE TITLE
android.view.InflateException

### ISSUE THREAD

**Issue by gkoulin** [EddyVerbruggen/nativescript-feedback#35]
Hello, I am getting `android.view.InflateException` when calling show on response from a promise.  Seems to be related to an older version of tapadoo alerter [https://github.com/Tapadoo/Alerter/issues/145](issue). Is it possible to upgrade to the most recent tapadoo alerter to fix this problem?

**Comment by EddyVerbruggen** [comment]
Can you find a workaround? Because I tried to upgrade, but their latest version was rewritten in Kotlin and that's currently not working in NativeScript.

**Comment by gkoulin** [comment]
No, unfortunately I was not able to find a workaround and went with nativescript-snackbar instead.

**Comment by dosomder** [comment]
@EddyVerbruggen Since NativeScript now supports kotlin, can this be updated? Besides this bug, the new version already has features like displaying at the bottom / center. Your fork of ISMessages also seems to be missing some fixes

**Comment by EddyVerbruggen** [comment]
It would be great if indeed someone would take the time and upgrade it.

**Comment by dosomder** [comment]
I'll see if I can make a PR for android at least

**Comment by dosomder** [comment]
I can't figure out how to update the tapadoo dependency. If I bump the version no alert is displayed anymore.

Looks like every version from 3.0.0 does not work. Doesn't seem like their API changed. Is there anything additional needed in include.gradle since the dependency is in kotlin now?

It looks like the js code does not get past the create() call.

Edit: If I add a try catch block I get the exception
` Error: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;`

Edit2: Figured it out. It was missing another dependency that is not really documented.
