### ISSUE TITLE
Color Icon

### ISSUE THREAD

**Issue by mendokar** [EddyVerbruggen/nativescript-feedback#7]
Good night, excuse me you can tell me if the color of the icon I can change it in the plugin, since when I put an icon it changes to white and I need it in black color.

Thank you.

**Comment by EddyVerbruggen** [comment]
Can you share the icon you tried, and on which platform(s) (iOS / Android / both)?

**Comment by mendokar** [comment]
![perfil](https://user-images.githubusercontent.com/26204958/29031407-cd0b83fa-7b53-11e7-956f-df738a5dbd47.png)

hi Eddy, thanks for you reply, i send url icon i used, is color black.

**Comment by EddyVerbruggen** [comment]
Is the problem on iOS, Android, or both?

**Comment by mendokar** [comment]
is both!

**Comment by EddyVerbruggen** [comment]
OK. Interestingly there seems to be no code on iOS to do something with the color. I hope to find some time to throw your image in my testapp.

**Comment by EddyVerbruggen** [comment]
I just downloaded your icon and dropped it in my demo app (the one included in this repo, I'll push the change as well). Only tested on iOS since you said it happens on both platforms. Behold this screenshot which looks good to me:

![simulator screen shot 8 aug 2017 17 38 20](https://user-images.githubusercontent.com/1426370/29080581-6725b354-7c60-11e7-8e42-5021783875ff.png)

**Comment by mendokar** [comment]
Hi Eddy thanks for the reply, but on Android I can not do the same thing as in IOS, check my attachment.
![img_20170808_114230438](https://user-images.githubusercontent.com/26204958/29083554-bf10007e-7c2e-11e7-8050-5823eefd08db.jpg)

**Comment by EddyVerbruggen** [comment]
So it's only a problem on Android then?

**Comment by mendokar** [comment]
yes

**Comment by EddyVerbruggen** [comment]
Since the problem is only on Android, and iOS is way too tricky to change an image's bitmap without doing a lot of unnecessary work for most cases, I've added a new `android.iconColor` property. See the [TypeScript example in the readme](https://github.com/EddyVerbruggen/nativescript-feedback/tree/bdc43e83b765a2c658962b4af5521ba2480ea06c#typescript-1) for its usage.

Available in 1.0.6 from npm now.
